# Generated by Django 5.0.7 on 2024-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tittle', models.CharField(max_length=100)),
                ('post_description', models.TextField(max_length=2500)),
                ('post_image', models.ImageField(upload_to='images/')),
                ('post_create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
