# Generated by Django 5.0.7 on 2024-07-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['id'], 'verbose_name': 'POST', 'verbose_name_plural': 'Posts'},
        ),
    ]
