# Generated by Django 5.0.7 on 2024-07-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_posts_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_tittle',
            new_name='post_title',
        ),
    ]
